#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#    Dec 05, 2022 12:37:16 PM -03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)


_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

class Toplevel3:
    def __init__(self):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        self.top = tk.Tk()
        self.top.geometry("630x508+314+153")
        self.top.minsize(120, 1)
        self.top.maxsize(1370, 749)
        self.top.resizable(1,  1)
        self.top.title("Tarefa de Colheita")
        self.top.configure(background="#171111")


        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.083, rely=0.043, relheight=0.923
                , relwidth=0.843)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#0F1011")

        self.Label1_2 = tk.Label(self.Frame1)
        self.Label1_2.place(relx=0.395, rely=0.107, height=41, width=114)
        self.Label1_2.configure(anchor='w')
        self.Label1_2.configure(background="#0F1011")
        self.Label1_2.configure(compound='left')
        self.Label1_2.configure(disabledforeground="#a3a3a3")
        self.Label1_2.configure(font="-family {Segoe UI} -size 20")
        self.Label1_2.configure(foreground="#ffffff")
        self.Label1_2.configure(text='''Colheita''')

        self.buttonSeg_2 = tk.Button(self.Frame1)
        self.buttonSeg_2.place(relx=0.113, rely=0.277, height=44, width=127)
        self.buttonSeg_2.configure(activebackground="beige")
        self.buttonSeg_2.configure(activeforeground="black")
        self.buttonSeg_2.configure(background="#858078")
        self.buttonSeg_2.configure(compound='left')
        self.buttonSeg_2.configure(disabledforeground="#a3a3a3")
        self.buttonSeg_2.configure(font="-family {Segoe UI} -size 16")
        self.buttonSeg_2.configure(foreground="#000000")
        self.buttonSeg_2.configure(highlightbackground="#d9d9d9")
        self.buttonSeg_2.configure(highlightcolor="black")
        self.buttonSeg_2.configure(pady="0")
        self.buttonSeg_2.configure(text='''Segunda''')

        self.buttonQua_2 = tk.Button(self.Frame1)
        self.buttonQua_2.place(relx=0.64, rely=0.277, height=44, width=127)
        self.buttonQua_2.configure(activebackground="beige")
        self.buttonQua_2.configure(activeforeground="black")
        self.buttonQua_2.configure(background="#858078")
        self.buttonQua_2.configure(compound='left')
        self.buttonQua_2.configure(disabledforeground="#a3a3a3")
        self.buttonQua_2.configure(font="-family {Segoe UI} -size 16")
        self.buttonQua_2.configure(foreground="#000000")
        self.buttonQua_2.configure(highlightbackground="#d9d9d9")
        self.buttonQua_2.configure(highlightcolor="black")
        self.buttonQua_2.configure(pady="0")
        self.buttonQua_2.configure(text='''Quarta''')

        self.buttonTer_2 = tk.Button(self.Frame1)
        self.buttonTer_2.place(relx=0.113, rely=0.448, height=44, width=127)
        self.buttonTer_2.configure(activebackground="beige")
        self.buttonTer_2.configure(activeforeground="black")
        self.buttonTer_2.configure(background="#858078")
        self.buttonTer_2.configure(compound='left')
        self.buttonTer_2.configure(disabledforeground="#a3a3a3")
        self.buttonTer_2.configure(font="-family {Segoe UI} -size 16")
        self.buttonTer_2.configure(foreground="#000000")
        self.buttonTer_2.configure(highlightbackground="#d9d9d9")
        self.buttonTer_2.configure(highlightcolor="black")
        self.buttonTer_2.configure(pady="0")
        self.buttonTer_2.configure(text='''Terça''')

        self.buttonQui_2 = tk.Button(self.Frame1)
        self.buttonQui_2.place(relx=0.64, rely=0.448, height=44, width=127)
        self.buttonQui_2.configure(activebackground="beige")
        self.buttonQui_2.configure(activeforeground="black")
        self.buttonQui_2.configure(background="#858078")
        self.buttonQui_2.configure(compound='left')
        self.buttonQui_2.configure(disabledforeground="#a3a3a3")
        self.buttonQui_2.configure(font="-family {Segoe UI} -size 16")
        self.buttonQui_2.configure(foreground="#000000")
        self.buttonQui_2.configure(highlightbackground="#d9d9d9")
        self.buttonQui_2.configure(highlightcolor="black")
        self.buttonQui_2.configure(pady="0")
        self.buttonQui_2.configure(text='''Quinta''')

        self.buttonSex_2 = tk.Button(self.Frame1)
        self.buttonSex_2.place(relx=0.377, rely=0.597, height=44, width=127)
        self.buttonSex_2.configure(activebackground="beige")
        self.buttonSex_2.configure(activeforeground="black")
        self.buttonSex_2.configure(background="#858078")
        self.buttonSex_2.configure(compound='left')
        self.buttonSex_2.configure(disabledforeground="#a3a3a3")
        self.buttonSex_2.configure(font="-family {Segoe UI} -size 16")
        self.buttonSex_2.configure(foreground="#000000")
        self.buttonSex_2.configure(highlightbackground="#d9d9d9")
        self.buttonSex_2.configure(highlightcolor="black")
        self.buttonSex_2.configure(pady="0")
        self.buttonSex_2.configure(text='''Sexta''')

        self.buttonDel_2 = tk.Button(self.Frame1)
        self.buttonDel_2.place(relx=0.038, rely=0.853, height=54, width=157)
        self.buttonDel_2.configure(activebackground="beige")
        self.buttonDel_2.configure(activeforeground="black")
        self.buttonDel_2.configure(background="#fd0000")
        self.buttonDel_2.configure(compound='left')
        self.buttonDel_2.configure(disabledforeground="#a3a3a3")
        self.buttonDel_2.configure(font="-family {Segoe UI} -size 16")
        self.buttonDel_2.configure(foreground="#000000")
        self.buttonDel_2.configure(highlightbackground="#d9d9d9")
        self.buttonDel_2.configure(highlightcolor="black")
        self.buttonDel_2.configure(pady="0")
        self.buttonDel_2.configure(text='''Delete''')

        self.buttonNextpage_2 = tk.Button(self.Frame1)
        self.buttonNextpage_2.place(relx=0.584, rely=0.853, height=54, width=197)

        self.buttonNextpage_2.configure(activebackground="beige")
        self.buttonNextpage_2.configure(activeforeground="black")
        self.buttonNextpage_2.configure(background="#4e62f1")
        self.buttonNextpage_2.configure(compound='left')
        self.buttonNextpage_2.configure(disabledforeground="#a3a3a3")
        self.buttonNextpage_2.configure(font="-family {Segoe UI} -size 16")
        self.buttonNextpage_2.configure(foreground="#000000")
        self.buttonNextpage_2.configure(highlightbackground="#d9d9d9")
        self.buttonNextpage_2.configure(highlightcolor="black")
        self.buttonNextpage_2.configure(pady="0")
        self.buttonNextpage_2.configure(text='''<< Pag Anterior''')
        
        self.top.mainloop()

Toplevel3()




