#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#    Dec 07, 2022 11:00:32 AM -03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)



_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

class topWDlevel4:
    def __init__(self):
        '''This class configures and populates the topWDlevel window.
           topWD is the topWDlevel containing window.'''

        self.topWD = tk.Tk()
        self.topWD.geometry("600x450+383+106")
        self.topWD.minsize(120, 1)
        self.topWD.maxsize(1370, 749)
        self.topWD.resizable(1,  1)
        self.topWD.title("Dia da semana")
        self.topWD.configure(background="#101111")


        self.Frame1WD = tk.Frame(self.topWD)
        self.Frame1WD.place(relx=0.183, rely=0.022, relheight=0.944
                , relwidth=0.675)
        self.Frame1WD.configure(relief='groove')
        self.Frame1WD.configure(borderwidth="2")
        self.Frame1WD.configure(relief="groove")
        self.Frame1WD.configure(background="#0F1014")

        self.labelWeekDay = tk.Label(self.Frame1WD)
        self.labelWeekDay.place(relx=0.296, rely=0.071, height=41, width=184)
        self.labelWeekDay.configure(anchor='s')
        self.labelWeekDay.configure(background="#0F1014")
        self.labelWeekDay.configure(compound='left')
        self.labelWeekDay.configure(disabledforeground="#a3a3a3")
        self.labelWeekDay.configure(font="-family {Segoe UI} -size 18")
        self.labelWeekDay.configure(foreground="#ffffff")
        self.labelWeekDay.configure(text='''Label''')

        self.labelResponseDay = tk.Label(self.Frame1WD)
        self.labelResponseDay.place(relx=0.049, rely=0.306, height=41, width=194)

        self.labelResponseDay.configure(activebackground="#f9f9f9")
        self.labelResponseDay.configure(anchor='s')
        self.labelResponseDay.configure(background="#0F1014")
        self.labelResponseDay.configure(compound='left')
        self.labelResponseDay.configure(disabledforeground="#a3a3a3")
        self.labelResponseDay.configure(font="-family {Segoe UI} -size 14")
        self.labelResponseDay.configure(foreground="#ffffff")
        self.labelResponseDay.configure(highlightbackground="#d9d9d9")
        self.labelResponseDay.configure(highlightcolor="black")
        self.labelResponseDay.configure(text='''Responsáveis do dia:''')

        self.labelUserDay = tk.Label(self.Frame1WD)
        self.labelUserDay.place(relx=0.519, rely=0.329, height=161, width=164)
        self.labelUserDay.configure(anchor='nw')
        self.labelUserDay.configure(background="#0f1014")
        self.labelUserDay.configure(compound='left')
        self.labelUserDay.configure(disabledforeground="#a3a3a3")
        self.labelUserDay.configure(font="-family {Segoe UI} -size 14")
        self.labelUserDay.configure(foreground="#ffffff")
        self.labelUserDay.configure(text='''Label''')

        self.buttonBackPage = tk.Button(self.Frame1WD)
        self.buttonBackPage.place(relx=0.247, rely=0.847, height=44, width=197)
        self.buttonBackPage.configure(activebackground="beige")
        self.buttonBackPage.configure(activeforeground="black")
        self.buttonBackPage.configure(background="#434667")
        self.buttonBackPage.configure(compound='left')
        self.buttonBackPage.configure(disabledforeground="#a3a3a3")
        self.buttonBackPage.configure(font="-family {Segoe UI} -size 14")
        self.buttonBackPage.configure(foreground="#000000")
        self.buttonBackPage.configure(highlightbackground="#d9d9d9")
        self.buttonBackPage.configure(highlightcolor="black")
        self.buttonBackPage.configure(pady="0")
        self.buttonBackPage.configure(text='''<< Pagina Anterior''')

        self.topWD.mainloop()


topWDlevel4()




