#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#    Dec 05, 2022 10:14:46 AM -03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)


_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

class Toplevel1:
    def __init__(self):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        
        self.top = tk.Tk()
        self.top.geometry("621x488+327+117")
        self.top.minsize(120, 1)
        self.top.maxsize(1370, 749)
        self.top.resizable(1,  1)
        self.top.title("Login window")
        self.top.configure(background="#2e2625")

        

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.167, rely=0.068, relheight=0.877
                , relwidth=0.691)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#0f1011")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.42, rely=0.093, height=61, width=84)
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#0f1011")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Times New Roman} -size 18")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(text='''Login''')

        self.userLabel = tk.Label(self.Frame1)
        self.userLabel.place(relx=0.21, rely=0.28, height=41, width=94)
        self.userLabel.configure(activebackground="#f9f9f9")
        self.userLabel.configure(anchor='w')
        self.userLabel.configure(background="#0f1011")
        self.userLabel.configure(compound='left')
        self.userLabel.configure(disabledforeground="#a3a3a3")
        self.userLabel.configure(font="-family {Times New Roman} -size 14")
        self.userLabel.configure(foreground="#ffffff")
        self.userLabel.configure(highlightbackground="#d9d9d9")
        self.userLabel.configure(highlightcolor="black")
        self.userLabel.configure(text='''Usuario:''')

        self.userEntry = tk.Entry(self.Frame1)
        self.userEntry.place(relx=0.21, rely=0.374, height=20, relwidth=0.592)
        self.userEntry.configure(background="white")
        self.userEntry.configure(disabledforeground="#a3a3a3")
        self.userEntry.configure(font="TkFixedFont")
        self.userEntry.configure(foreground="#000000")
        self.userEntry.configure(insertbackground="black")

        self.passwordLabel = tk.Label(self.Frame1)
        self.passwordLabel.place(relx=0.21, rely=0.467, height=41, width=94)
        self.passwordLabel.configure(activebackground="#f9f9f9")
        self.passwordLabel.configure(anchor='w')
        self.passwordLabel.configure(background="#0f1011")
        self.passwordLabel.configure(compound='left')
        self.passwordLabel.configure(disabledforeground="#a3a3a3")
        self.passwordLabel.configure(font="-family {Times New Roman} -size 14")
        self.passwordLabel.configure(foreground="#ffffff")
        self.passwordLabel.configure(highlightbackground="#d9d9d9")
        self.passwordLabel.configure(highlightcolor="black")
        self.passwordLabel.configure(text='''Senha:''')

        self.passwordEntry = tk.Entry(self.Frame1)
        self.passwordEntry.place(relx=0.21, rely=0.561, height=20
                , relwidth=0.592)
        self.passwordEntry.configure(background="white")
        self.passwordEntry.configure(disabledforeground="#a3a3a3")
        self.passwordEntry.configure(font="TkFixedFont")
        self.passwordEntry.configure(foreground="#000000")
        self.passwordEntry.configure(highlightbackground="#d9d9d9")
        self.passwordEntry.configure(highlightcolor="black")
        self.passwordEntry.configure(insertbackground="black")
        self.passwordEntry.configure(selectbackground="#c4c4c4")
        self.passwordEntry.configure(selectforeground="black")

        self.buttonLogin = tk.Button(self.Frame1)
        self.buttonLogin.place(relx=0.35, rely=0.678, height=44, width=137)
        self.buttonLogin.configure(activebackground="beige")
        self.buttonLogin.configure(activeforeground="black")
        self.buttonLogin.configure(background="#00b700")
        self.buttonLogin.configure(compound='left')
        self.buttonLogin.configure(disabledforeground="#a3a3a3")
        self.buttonLogin.configure(font="-family {Segoe UI} -size 18")
        self.buttonLogin.configure(foreground="#000000")
        self.buttonLogin.configure(highlightbackground="#d9d9d9")
        self.buttonLogin.configure(highlightcolor="black")
        self.buttonLogin.configure(pady="0")
        self.buttonLogin.configure(text='''Login''')

        self.buttonRegister = tk.Button(self.Frame1)
        self.buttonRegister.place(relx=0.35, rely=0.841, height=44, width=137)
        self.buttonRegister.configure(activebackground="beige")
        self.buttonRegister.configure(activeforeground="black")
        self.buttonRegister.configure(background="#5b5b91")
        self.buttonRegister.configure(compound='left')
        self.buttonRegister.configure(disabledforeground="#a3a3a3")
        self.buttonRegister.configure(font="-family {Segoe UI} -size 18")
        self.buttonRegister.configure(foreground="#000000")
        self.buttonRegister.configure(highlightbackground="#d9d9d9")
        self.buttonRegister.configure(highlightcolor="black")
        self.buttonRegister.configure(pady="0")
        self.buttonRegister.configure(text='''Cadastrar''')
        self.top.mainloop()

Toplevel1()