#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.5
#  in conjunction with Tcl version 8.6
#    Dec 05, 2022 12:13:11 PM -03  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)


_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

class Toplevel2:
    def __init__(self,):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        self.top = tk.Tk()
        self.top.geometry("630x508+289+171")
        self.top.minsize(120, 1)
        self.top.maxsize(1370, 749)
        self.top.resizable(1,  1)
        self.top.title("tarefa de irrigação")
        self.top.configure(background="#171111")



        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.083, rely=0.043, relheight=0.923
                , relwidth=0.843)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#0F1011")

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.395, rely=0.107, height=41, width=114)
        self.Label1.configure(anchor='w')
        self.Label1.configure(background="#0F1011")
        self.Label1.configure(compound='left')
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font="-family {Segoe UI} -size 20")
        self.Label1.configure(foreground="#ffffff")
        self.Label1.configure(text='''Irrigação''')

        self.buttonSeg = tk.Button(self.Frame1)
        self.buttonSeg.place(relx=0.113, rely=0.277, height=44, width=127)
        self.buttonSeg.configure(activebackground="beige")
        self.buttonSeg.configure(activeforeground="black")
        self.buttonSeg.configure(background="#858078")
        self.buttonSeg.configure(compound='left')
        self.buttonSeg.configure(disabledforeground="#a3a3a3")
        self.buttonSeg.configure(font="-family {Segoe UI} -size 16")
        self.buttonSeg.configure(foreground="#000000")
        self.buttonSeg.configure(highlightbackground="#d9d9d9")
        self.buttonSeg.configure(highlightcolor="black")
        self.buttonSeg.configure(pady="0")
        self.buttonSeg.configure(text='''Segunda''')

        self.buttonQua = tk.Button(self.Frame1)
        self.buttonQua.place(relx=0.64, rely=0.277, height=44, width=127)
        self.buttonQua.configure(activebackground="beige")
        self.buttonQua.configure(activeforeground="black")
        self.buttonQua.configure(background="#858078")
        self.buttonQua.configure(compound='left')
        self.buttonQua.configure(disabledforeground="#a3a3a3")
        self.buttonQua.configure(font="-family {Segoe UI} -size 16")
        self.buttonQua.configure(foreground="#000000")
        self.buttonQua.configure(highlightbackground="#d9d9d9")
        self.buttonQua.configure(highlightcolor="black")
        self.buttonQua.configure(pady="0")
        self.buttonQua.configure(text='''Quarta''')

        self.buttonTer = tk.Button(self.Frame1)
        self.buttonTer.place(relx=0.113, rely=0.448, height=44, width=127)
        self.buttonTer.configure(activebackground="beige")
        self.buttonTer.configure(activeforeground="black")
        self.buttonTer.configure(background="#858078")
        self.buttonTer.configure(compound='left')
        self.buttonTer.configure(disabledforeground="#a3a3a3")
        self.buttonTer.configure(font="-family {Segoe UI} -size 16")
        self.buttonTer.configure(foreground="#000000")
        self.buttonTer.configure(highlightbackground="#d9d9d9")
        self.buttonTer.configure(highlightcolor="black")
        self.buttonTer.configure(pady="0")
        self.buttonTer.configure(text='''Terça''')

        self.buttonQui = tk.Button(self.Frame1)
        self.buttonQui.place(relx=0.64, rely=0.448, height=44, width=127)
        self.buttonQui.configure(activebackground="beige")
        self.buttonQui.configure(activeforeground="black")
        self.buttonQui.configure(background="#858078")
        self.buttonQui.configure(compound='left')
        self.buttonQui.configure(disabledforeground="#a3a3a3")
        self.buttonQui.configure(font="-family {Segoe UI} -size 16")
        self.buttonQui.configure(foreground="#000000")
        self.buttonQui.configure(highlightbackground="#d9d9d9")
        self.buttonQui.configure(highlightcolor="black")
        self.buttonQui.configure(pady="0")
        self.buttonQui.configure(text='''Quinta''')

        self.buttonSex = tk.Button(self.Frame1)
        self.buttonSex.place(relx=0.377, rely=0.597, height=44, width=127)
        self.buttonSex.configure(activebackground="beige")
        self.buttonSex.configure(activeforeground="black")
        self.buttonSex.configure(background="#858078")
        self.buttonSex.configure(compound='left')
        self.buttonSex.configure(disabledforeground="#a3a3a3")
        self.buttonSex.configure(font="-family {Segoe UI} -size 16")
        self.buttonSex.configure(foreground="#000000")
        self.buttonSex.configure(highlightbackground="#d9d9d9")
        self.buttonSex.configure(highlightcolor="black")
        self.buttonSex.configure(pady="0")
        self.buttonSex.configure(text='''Sexta''')

        self.buttonDel = tk.Button(self.Frame1)
        self.buttonDel.place(relx=0.038, rely=0.853, height=54, width=157)
        self.buttonDel.configure(activebackground="beige")
        self.buttonDel.configure(activeforeground="black")
        self.buttonDel.configure(background="#fd0000")
        self.buttonDel.configure(compound='left')
        self.buttonDel.configure(disabledforeground="#a3a3a3")
        self.buttonDel.configure(font="-family {Segoe UI} -size 16")
        self.buttonDel.configure(foreground="#000000")
        self.buttonDel.configure(highlightbackground="#d9d9d9")
        self.buttonDel.configure(highlightcolor="black")
        self.buttonDel.configure(pady="0")
        self.buttonDel.configure(text='''Delete''')

        self.buttonNextpage = tk.Button(self.Frame1)
        self.buttonNextpage.place(relx=0.584, rely=0.853, height=54, width=197)
        self.buttonNextpage.configure(activebackground="beige")
        self.buttonNextpage.configure(activeforeground="black")
        self.buttonNextpage.configure(background="#4e62f1")
        self.buttonNextpage.configure(compound='left')
        self.buttonNextpage.configure(disabledforeground="#a3a3a3")
        self.buttonNextpage.configure(font="-family {Segoe UI} -size 16")
        self.buttonNextpage.configure(foreground="#000000")
        self.buttonNextpage.configure(highlightbackground="#d9d9d9")
        self.buttonNextpage.configure(highlightcolor="black")
        self.buttonNextpage.configure(pady="0")
        self.buttonNextpage.configure(text='''Proxima pag >>''')

        self.top.mainloop()


Toplevel2()